xapi-project/xcp-idl

- xen/xenops_interface.ml
> [RFC] xen: Add a "floppy" type, alongside cdrom and hard disk

- xen/xenops_interface.ml
Signed-off-by: Hui Zhang <hui.zhang@citrix.com>
> CP-10203: XenAPI: api call for RDP on/off request

- xen/xenops_interface.ml
Add new video_card representing IGD_passthrough.
> CP-10125: Add IGD_passthrough to video_card

- opam
> opam: add dependency to xapi-backtrace

- storage/storage_interface.ml
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
> Forward port read caching API

- .travis.yml
- lib/cohttp_posix_io.ml
- lib/xcp_client.ml
- lib/xcp_service.ml
- opam
Signed-off-by: David Scott <dave.scott@citrix.com>
> Update to cohttp.0.15.2

- memory/memory_interface.ml
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>
> [CA-155888] add a query reservation id interface

- lib/xcp_client.ml
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
- Minor typo fix
Signed-off-by: David Scott <dave.scott@citrix.com>
> Read the whole of the HTTP request, not just the first chunk

- xen/xenops_interface.ml
1. Merge code change of upgrade logic to xenops_interface
2. Add auto_update_drivers in Vm.t
> CP-12148: Replace platform: pci_pv to new field auto_update_drivers 

- lib/open_uri.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> DNS lookup for URIs

- xen/xenops_interface.ml
Signed-off-by: chengz <cheng.zhang@citrix.com>
> CP-12148: Add auto_update_drivers to Vm.t

- network/network_interface.ml
This call will return the PIF capabilities
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>
> CP-12093: Add PIF.get_capabilities RPC to Network Interface

- rrd/rrd_interface.ml
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>
> CP-13481: Add SR level RRD APIs to IDL

- lib/xcp_service.ml
The main service config file can contain sensible defaults, while
site-specific overrides can be placed in a fragment file. This also
allows packages to modify the configuration of another package,
without worry that the changes will be lost over upgrade.
> CP-12909: Support a directory full of configuration file fragments

- storage/storage_interface.ml
> Plumb through new SR.stat fields "clustered" and "health"

- rrd/rrd_interface.ml
This PR is just for review, It need to be merged into trunk-thin-lvhd-2 branch.
> CP-13995: Adding new xcp-rrdd interfaces for sr-level rrds archiving.

- xen/xenops_interface.ml
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> CP-14811: Add function to upgrade old-style VM feature sets

- xen/xenops_interface.ml
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> CP-14811: Add old-style feature mask to output of Host.stat

- rrd/rrd_interface.ml
Now that the WLB tests are passing, I think this is good to go in.
> CP-12141: Remove master/slave knowledge from RRDD

- lib_test/device_number_test.ml
- lib_test/test.ml
This has been resurrected from xenopsd.git
> Add device_number_test.ml

- lib/xcp_service.ml
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
> CP-15132/CA-204487: daemonize: Wait for parent to exit before writing PID file

- lib/xcp_service.ml
Reverts xapi-project/xcp-idl#116
> Revert "CP-15132/CA-204487: daemonize: Wait for parent to exit before writing PID file"

- CHANGES
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> CHANGES: Update for release 1.0.1

- network/network_interface.ml
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>
> CA-201728: Add new interface `is_vlan_in_use`

- xen/xenops_interface.ml
Reverts xapi-project/xcp-idl#127
> Revert "CP-18289 add nomigrate, nested_virt booleans to xenops state"

- network/network_interface.ml
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>
> CA-223676: Add `get_physical_interfaces` to Network_interface.

- network/network_interface.ml
Reverts xapi-project/xcp-idl#138
> Revert "CA-223676: Add `get_physical_interfaces` to Network_interface."

- xen/xenops_types.ml
> CP-21148: Update mxgpu xenops type

- .travis.yml
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>
> .travis.yml: Use xs-opam repo over deprecated opam-repo-dev

- .travis.yml
- README.md
> travis: update build structure and introduce coverage

- gpumon/gpumon_interface.ml
> CP-20677: document the pgpu_address format in gpumon

- storage/storage_interface.ml
- storage/storage_skeleton.ml
This should be merged together with https://github.com/xapi-project/xen-api/pull/3093 (otherwise the build will break).
> [merge together with xen-api/3093] Merge first part of CBT feature branch into master

- .merlin
> Update .merlin file

- .travis.yml
> Update compiler in travis file

- network/network_interface.ml
Signed-off-by: Liang Dai <liang.dai1@citrix.com>
> REQ-230 merge feature branch to master

- xen/xenops_interface.ml
1. Add vusb to xenops_interface with plug/unplug interface
Signed-off-by: Taoyong Ding <taoyong.ding@citrix.com>
> CP-24549: Add vusb to xenops_interface

- Makefile
Based on https://github.com/xapi-project/xen-api/blob/master/Makefile#L73
> jbuilderize: obey DESTDIR in make install

- storage/jbuild
> storage_interface: add missing dependency in jbuild file

- network/network_interface.ml
> Network_interface: remove unused functions

- lib/jbuild
- lib/xcp_pci.ml
- network/network_interface.ml
- xen/xenops_interface.ml
- xen/xenops_types.ml
This change is to:
Factoring out PCI address to common lib
SRIOV interface add
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>
> Factoring out PCI address to common lib and add SRIOV interface

- network/network_interface.ml
Add new interface to get pci bus path
> CP-26333 Add PIF.pci field for network sriov feature

- network/network_interface.ml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xcp-idl/192)
> Differentiate the sriov_result into three kinds.

- lib/syslog.ml
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
> String.{lowercase -> lowercase_ascii}, strip whitespace

- lib/xcp_service.ml
- network/network_stats.ml
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
> Remove redundant (|>) definition

- storage/storage_interface.ml
> Add SR UUID to sr_info

- lib/jbuild
- lib/xcp_pci.ml
- network/network_interface.ml
- xen/xenops_interface.ml
- xen/xenops_types.ml
Merge feature SR-IOV to master
BST passed in job 81743
BVT passed in job 81742
> Merge feature SR-IOV to master

- gpumon/gpumon_cli.ml
- memory/memory_cli.ml
- network/jbuild
- network/network_cli.ml
- v6/v6_cli.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Fix the memory CLI and add a network one

- lib/open_uri.ml
- lib/posix_channel.ml
> CA-289145: Close socket if error occurs when connecting

- lib/debug.ml
`log_and_ignore_exn` just called `log_backtrace` which gave us a backtrace
in the logs, but the actual exception message was lost, which can be
quite important for debugging.
Use the outer `log_backtrace_exn` which logs both the backtrace and the
message, using the improved backtraces saved by the backtrace module.
This is related to https://github.com/xapi-project/stdext/pull/32
> CP-28365: do not lose the exception text in log_and_ignore_exn

- cluster/cluster_interface.ml
> CP-29027: cluster_interface: Add startup_finished to diagnostics

- cluster/jbuild
- example/jbuild
- gpumon/jbuild
- lib/jbuild
- lib_test/jbuild
- memory/jbuild
- network/jbuild
- rrd/jbuild
- v6/jbuild
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Remove calls to ocamlfind from within jbuild files

- Makefile
- xcp.opam
- use Dune
- update opam files
> Use Dune, update opam files

- xen/xenops_interface.ml
> Fix clerical error of xenops exception

- storage/storage_interface.ml
> Fix indentation

- network/network_interface.ml
> network_interface: add Interface_does_not_exist error

- xen/xenops_types.ml
These have been reviewed previously on the `uefi` branch, I have rebased and squashed the commits (too many conflicts, and the commit messages got out of date).
Needs to be merged together with:
https://github.com/xapi-project/xen-api/pull/3728
https://github.com/xapi-project/xenops-cli/pull/27
xenopsd doesn't require any changes for the branch to build and run in Bios merge, those changes will come later.
I've run a Ring3 BST on this and it was all green.
BIOS boot: if absent or set to `Bios`
UEFI boot: if set to ``Uefi _`
The field needs to have a default value, otherwise xenopsd fails to
import existing VMs that do not have this field.
The NVRAM will be used initially for UEFI guests to store:
`EFI-variables-on-boot` and `EFI-variables-backend`.
This is stored inside a record to be …
> CP-28301, CP-28659, CP-28662: add firmware type and NVRAM parameter for xenopsd

- xapi-idl.opam
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>
> Added missing build instruction.

- xen/xenops_interface.ml
Signed-off-by: Taoyong Ding <taoyong.ding@citrix.com>
> CA-308834: backport CA-307829 on havana

- lib/open_uri.ml
- lib/posix_channel.ml
> XSI-312 CA-289145: Close socket if error occurs when connecting

- xen/xenops_types.ml
- Delete 'config_file' since no longer used.
- Add virtual_pci_address and type_id.
Signed-off-by: Lin Liu <lin.liu@citrix.com>
Signed-off-by: Min Li <min.li1@citrix.com>
> REQ-720: CP-31058: Update nvidia type.

- xen/xenops_types.ml
Signed-off-by: Min Li <min.li1@citrix.com>
> CP-31160: Add 'config_file' back to IDL.

- gpumon/gpumon_interface.ml
- lib_test/test_data/gpumon/requests/get_vgpu_metadata.request.0
- xen/xenops_types.ml
Feature integration to master.
> REQ-720: Support multiple vGPUs in one VM

- .travis.yml
Use debian-unstable for access to xxhash.
> Simplify Travis setup

- xen/xenops_types.ml
> CA-321983: use defaults or options for new nvidia vgpu fields

- dune-project
- lib/xcp_service.ml
* 1b71d73 Silence preprocess warnings                                      
* 8cc5fd2 Avoid deprecated Re.get_all_ofs
> Maintenance: remove and silence warnings

- Makefile
- storage/storage_test.ml
> Simplify Makefile

- storage/dune
- storage/storage_test.ml
@lindig noticed that it wasn't building for quite a while, found by doing `dune build @all`.
Make it part of the regular build again, and fix it.
> Fix storage test

- lib/debug.ml
- lib/debug.mli
> CA-326244: Debug: Remove unused get_all_debug_keys and its mutex

- lib/debug.ml
By using a reference to an immutable Map instead of a Hashtable.
> CA-326244: don't take thread local table lock during logging

- lib/debug.ml
> CA-326244: Debug: Remove unnecessary facility mutex

- xen/xenops_interface.ml
Signed-off-by: lippirk <ben.anson@citrix.com>
> CA-328130 add speed to Vusb record

- lib/dune
- lib/scheduler.ml
- lib/scheduler.mli
- lib/task_server.ml
- lib_test/channel_test.ml
- lib_test/scheduler_test.ml
- memory/memory_interface.ml
- misc/channel_helper.ml
- misc/dune
- storage/storage_interface.ml
- storage/storage_test.ml
- xapi-idl.opam
Explanations in individual commit messages.
> CA-338201/CA-337546: use single persistent pipe per scheduler and Mtime

- lib/dune
- lib/task_server.ml
- lib/updates.ml
- lib/xcp_service.ml
- xapi-idl.opam
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> CP-33121: Do not use stdext's monadic

- lib/debug.ml
A failing HOST.stat call logged just the exception, but not the
backtrace:
```
Sep  1 10:55:07 localhost xenopsd-xc: [error||72 ||backtrace] dbsync (update_env) R:a771d46f95c9 failed with exception Xenctrlext.Unix_error(57, "105: No buffer space availa
ble")
Sep  1 10:55:07 localhost xenopsd-xc: [error||72 ||backtrace] Raised Xenctrlext.Unix_error(57, "105: No buffer space available")
Sep  1 10:55:07 localhost xenopsd-xc: [error||72 ||backtrace] 1/1 xenopsd-xc Raised at file (Thread 72 has no backtrace table. Was with_backtraces called?, line 0
Sep  1 10:55:07 localhost xenopsd-xc: [error||72 ||backtrace]
```
Although with_backtraces was definitely called by
Debug.with_thread_associated:
```
let stat _ dbg =
Debug.with_thread_associated dbg
(fun () ->
debug "HOST.stat" ;
let module B = …
```
> Fix backtraces in xenopsd-xc

- lib_test/idl_test_common.ml
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> CP-34942: compatibility with rpclib 8

- xen/xenops_interface.ml
* CA-347560: Add VM.import_metadata_async
Backport of https://github.com/xapi-project/xcp-idl/pull/319
> backport! (stockholm) XSI-555/CA-347560

- lib/open_uri.ml
- lib/posix_channel.ml
- misc/channel_helper.ml
- replace `gethostbyname` by `getaddrinfo`
- don't assume all ip connexion are IPv4
> Handle IPv6

- lib/xcp_const.ml
Signed-off-by: Ming Lu <ming.lu@citrix.com>
> CP-36919,CP-36711: Update ciphers used by stunnel/XAPI for Trunk
