xen/device_number.ml, xen/device_number.mli, xen/xenops_interface.ml
Original pull request: https://github.com/xapi-project/xcp-idl/pull/46
Updated with a new floppy bus type, as qemu wants floppy drives to be on the "floppy" bus, rather than "ide".
Note that this means that `Device_number.to_disk_number` is no longer unique (e.g. "fda" and "xvda" are both disk number "0"), and should not be used to identify disks. [This is the subject of a bugfix in xen-api -- see pull request https://github.com/xapi-project/xen-api/pull/2068]
=> [RFC] xen: Add a "floppy" type, alongside cdrom and hard disk (take #2)

network/network_interface.ml
This call will return the status of PIF
whether it supports FCoE
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>
=> CP-12093: Add PIF_metrics.is_fcoe_supported RPC to Network Interface

xen-api-plugin/service.md
The login_with_password XenAPI call takes an "originator"
string as its fourth parameter.
If a client does this, then it gets its own pool of xapi sessions.
Moreover it will not have its xapi sessions destroyed prematurely
as a result of some other misbehaving client that keeps creating
sessions and not logging out of them.
This patch adds the "originator" to all invokes of
login_with_password.
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>
=> CP-9895: Added originator for xapi login_with_password

storage/storage_interface.ml, storage/storage_skeleton.ml
Storage backends will be expected to be able to persist these human-readable
values somewhere, so they can be retrieved over a SR.forget / SR.introduce.
=> storage: add set_name_label and set_name_description

storage/storage_interface.ml, storage/storage_skeleton.ml
Since this is special-cased in the SMAPIv1, it needs passing through
the SMAPIv2. It won't be implemented in the SMAPIv3.
=> storage: add VDI.introduce

storage/storage_interface.ml
The `required_cluster_stack` allows a storage implementation to declare
that it needs a particular cluster stack (HA implementation) to run.
For example, a hypothetical OCFS2 adapter would need either O2CB or
corosync/pacemaker.
Signed-off-by: David Scott <dave.scott@citrix.com>
=> CP-13697: storage: add `required_cluster_stack`

example/example.ml, lib/xcp_service.ml
=> Use org.xen.xapi as the queue name prefix

rrd/rrd_interface.ml
The interface before this patch involved asking an RRD server where for the
path that it would store the archive should it succeed, then an archive call,
and then checking that the file was there since in the error case there are no
exceptions to return.
Similarly for restoring from an archive a client would have to ask the server
where it expects these archives to be to restore, put the file there and then
call restore.
This patch simplifies the interface such that:
* The restore function takes a path to restore from in addition to the uuid;
* The archive function returns a path to the archive;
* An exception is defined so that we don't have to silently fail.
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
=> CA-185923: Use a sane API for archiving/pushing SR RRDs

xen/xenops_interface.ml
set-ip(v4,v6)-configuration
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>
=> CP-15358: support external ip address setting

lib/xcp_service.ml, lib/xcp_service.mli
The startup function, if specified, is executed before the PID file is written.
If `maybe_daemonize` decides not to daemonise, it still executes the startup
function.
=> Accept an optional startup function in (maybe_)daemonize

.travis.yml, lib/xcp_service.ml, opam
The two calls to Unix.dup are intended to point stdout and stderr at
/dev/null - this will normally be the case, as Unix.dup will open the
next available file descriptor and stdout/stderr have just been closed.
However, there are many ways this can go wrong - if an open() happens
in another thread it could mean that...
* nullfd <> Unix.stdin - this is checked for, but there is no error
handling if this fails
* one or both of the Unix.dup calls do not point stdout/stderr at
/dev/null as intended, but instead open new file descriptors.
This change instead uses Unix.dup2 which atomically closes the second
file descriptor and copies it from the first. This also allows the
explicit calls to Unix.close to be removed. Finally, nullfd is closed as
it is not needed after the calls to Unix.dup2.
=> CA-208547: Avoid races in pointing stdin/stdout/stderr at /dev/null

xen/xenops_interface.ml
The two values will be used to inform xapi about the mobility of a VM.
A VM cannot migrate if it uses nested virtualisation or is explicitly
configured to not migrate.
=> CP-18289 add nomigrate, nested_virt booleans to xenops state

xen/xenops_interface.ml
When updating the MTU of a VIF it can happen that the VM `domid` is still out of sync. We can use the correct `domid` value passing it via `xenopsd` as a field in `VIF.stat`.
=> [CP-18781] Add device information in VIF.state

example/example.ml, lib/cohttp_posix_io.ml, lib/posix_channel.ml, lib/syslog.ml, lib_test/debug_test.ml, network/network_stats.ml
Fix the warnings emitted by version 4.02.2 of the OCaml compiler. (I used the [xs-shipyard docker image](https://github.com/lindig/xs-shipyard) for compilation.)
I should probably squash the commits in case they are merged, but multiple smaller commits might be easier to review in the meantime.
=> Fix OCaml compiler warnings

xen/xenops_interface.ml, xen/xenops_types.ml
Broaden the Vgpu.implementation type to include MxGPU implementations.
The mxgpu type contains the configuration values to be passed to qemu.
=> CP-20431: MxGPU in Xenops_interface.Vgpu

gpumon/gpumon_interface.ml
This will allow us to catch issues during the initialisation of the library and at runtime.
=> Introduce exceptions

gpumon/gpumon_interface.ml
This should help to avoid confusion and prevent potential name clashes if similar features are implemented for other manufacturers.
=> gpumon_interface: namespace nvidia-only interface

gpumon/gpumon_interface.ml
The old version was specifying the type of the Nvidia module, we need the struct instead.
Also, if the types are contained in the module the camlp4 rpc generation fails to create the necessary helpers.
=> gpumon_interface: extract types to workaround a camlp4 issue

gpumon/gpumon_interface.ml
Unfortunately the exception inside a sub-module is not usable in `try..with` statements.
=> gpumon_interface: extract Nvidia exception

xen/xenops_interface.ml
This goes hand in hand with https://github.com/xapi-project/xen-api/pull/3073
=> [CP-22597] Add other_config to vgpu records for temporary migration vgpu_map

xen/xenops_interface.ml
This ended up here as an oversight. The `other-config` map used for the
vgpu migration is in fact the one in xapi database and does not require
further changes to the idl or to xenopsd.
This reverts commit 5dedafa107f7a9117ba7f9aa60c53add94200721.
=> Revert "[CP-22597] Add other_config to vgpu records"

network/network_interface.ml
Signed-off-by: Liang Dai <liang.dai1@citrix.com>
=> CP-23093: Add igmp_snooping field for bridge

storage/storage_interface.ml, storage/storage_skeleton.ml
Because the latter is clearer. People found the function name
export_changed_blocks confusing, because it suggested that the actual
data of the changed blocks will be "exported".
=> Rename VDI.export_changed_blocks to VDI.list_changed_blocks

storage/storage_client.ml, storage/storage_interface.ml
To enable SR scan to correctly set this parameter in case the VDI isn't
yet in xapi's database, instead of defaulting to false. This change only
affect's xapi, because SMAPIv2 is an internal storage interface that
only exists in xapi.
=> CP-22446: Add cbt_enabled parameter to vdi_info

gpumon/gpumon_interface.ml
This exposes a new function implemented in gpumon for checking the
compatibility of vGPU and pGPU. This  PR should be merged before 
https://github.com/xenserver/gpumon/pull/25 is merged.
=> CP-24185 add gpumon_if.get_pgpu_vgpu_compatibility

Makefile, lib/coverage/disabled.ml, lib/coverage/enabled.ml, lib/jbuild, lib/xcp_coverage.mli, lib/xcp_service.ml
Long running daemons like xapi, xenopsd, etc. can benefit from dumping coverage
data at runtime, not only at exit.
Instead of duplicating the code in each daemon provide library code, that:
* logs a message on startup so we know it is active
* set BISECT_FILE env var to dump coverage in the appropriate place
(the default of dumping in the current directory is not good for a daemon)
* listen on `org.xen.xapi.coverage.<name>` message queue for
runtime coverage dump commands
* all daemons that use `Xcp_service.configure2` will get this automatically
This code is a no-op by default, only enabled when `make runtime-coverage` is used,
i.e. normally nothing listens on the "org.xen.xapi.coverage" message queue.
It also provides a coverage dispatcher listening on "org.xen.xapi.coverage.dispatch" …
=> CP-22945: runtime coverage dumping support for Xcp_service

lib_test/updates_test.ml
This fixes a test that broke after the latest rpc update.
The new json serialization drops unneeded characters (e.g. pretty print newlines and spaces),
so tests that are based on specific output strings can break without any real breakage.
In this case the failure was due to:
```
got ->      {"updates":[{"id":1,"v":"[\"Foo\",\"a\"]"}],"barriers":[[1,2,[{"id":1,"v":"[\"Foo\",\"a\"]"}]]]}
expected -> {"updates": [{"id": 1, "v": "[\"Foo\", \"a\"]"}], "barriers": [[1, 2, [{"id": 1, "v": "[\"Foo\", \"a\"]"}]]]}
```
The two json representations are matching but we were relying on the
wrong invariant.
This change makes the test more robust with respect to this kind of
changes, although still not perfect (the values of v are still json
strings).
Signed-off-by: Marcello Seri …
=> updates_test: do not rely on json as a string but compare the Rpc structure

lib/coverage/enabled.ml, lib/jbuild, lib/xcp_client.ml, lib/xcp_service.ml, xcp.opam
This depends on xapi-project/message-switch#37; please do not merge before xs-opam is updated.
=> CP-26471: Renamed library after porting it to jbuilder.

lib/coverage/enabled.ml
Trying to use `make runtime-coverage` from the spec instead of calling jbuilder directly, and it was failing on this line due to `jbuilder build --dev`.
With this warning fixed `make runtime-coverage` works.
=> CP-22945: coverage: fix compiler warning on unused variable

Makefile
The `--dev` flag injects `ocamlc` flags that are not under our control. If we want to make the build fail on warning we should do it by adding `-warn-error -a` or whatever appropriate in the `jbuild` files instead.
We should still retain the `build` target, to be used when developing to fix unnecessary warnings.
=> Makefile: do not use --dev in the release build

v6/jbuild, v6/v6_cli.ml, v6/v6_client.ml, v6/v6_interface.ml
This PR is the second of three which port the licensing daemon to PPX:
1. xcp-idl: [port V6d interface to use PPX](https://github.com/xapi-project/xcp-idl/pull/186)
2. xapi: [update references to v6 interface](https://github.com/xapi-project/xen-api/pull/3391)
3. v6d: port daemons to ppx.
This PR in particular includes the following changes:
- ports v6d_interface from Camlp4 to PPX
- updates the v6 jbuild file to no longer use camlp4
- updates v6_client error handling
Possible follow-up: A .mli file defining the v6 interface
Note: CP-26098 is part of REQ-417
=> CP-26098: Port v6d interface from Camlp4 to PPX

xen/xenops_interface.ml
A new network backend type for network SR-IOV VF backed vif is added.
This backend type also introduces a new filed 'vlan' in 'Vif.t'.
Signed-off-by: Ming Lu ming.lu@citrix.com
=> CP-25794: Add new network backend type for network SR-IOV

lib/channel_helper.ml, xcp.opam
lib/channel_helpers.ml still uses deprecated `Lwt_unix.Versioned.bind_2`, causing `make test` to fail.
This PR updates to `Lwt_unix.bind`.
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
=> Lwt_unix.{Versioned.bind_2 -> bind}

.coverage.sh
Copy over all the bisect files, include all folders and avoid using arrays.
=> coverage: be less smart

cluster/jbuild, memory/jbuild, v6/jbuild
This PR builds all daemon debugger CLI tools with `jbuilder runtest`/`make test`.
It also removes unnecessary PPX rewriter dependencies from `cluster/jbuild`
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
=> Build CLI tools with runtest

gpumon/gpumon_cli.ml, gpumon/gpumon_client.ml, gpumon/gpumon_interface.ml, gpumon/jbuild
This is the first of 3 PRs to port the GPU monitoring daemon gpumon to use PPX-based code generation for RPCs. This PR updates the Gpumon interface and client to use PPX, and adds a dev/debugging CLI.
(Core BVT and Ring3 BST have passed)
PRs involved:
1. Port Gpumon IDL to PPX (this one)
2. [Update Xapi to use upgraded Gpumon interface](https://github.com/xapi-project/xen-api/pull/3418)
3. [Port Gpumon daemon](https://github.com/xenserver/gpumon/pull/29)
=> CP-26717: Port Gpumon to PPX-based RPCs

storage/storage_client.ml, storage/storage_interface.ml
This is part of the SMAPIv3 interface  change from `feature/REQ477/master` branch (that branch had 2 full nightlies run on it).
SMAPIv3 requires a uuid returned from SR.create, this PR together with the one for XAPI changes SMAPIv2 to allow for that (SMAPIv1 is not affected).
This is a breaking API change for SMAPIv3 plugins!
Also expose the `sharable` field to SMAPIv3 (required for the HA statefile and redolog), internally XAPI already tracked this field. SMAPIv1 looked in `sm-config` to find this out, no change there.
This PR needs to be merged together with these ones otherwise the build breaks:
xapi-project/sm-cli#26
xapi-project/xapi-storage#70
xapi-project/xapi-storage-script#56
https://github.com/xapi-project/xen-api/pull/3433
I've done a build of these changes separately on the …
=> [477 idl part2] SR.create API change and sharable flag

gpumon/gpumon_interface.ml, memory/memory_interface.ml, v6/v6_interface.ml
This is updating `memory`, `gpumon` and `v6`, recently ported to the new ppx interface.
This is not updatding `clusterd` that uses a slightly different error reporting and may noot need it (ping @edwintorok).
=> CA-283754: ppxified interfaces, do not discard internal errors

gpumon/gpumon_interface.ml, memory/memory_interface.ml, network/network_interface.ml, v6/v6_interface.ml
This logs all errors flowing across the interface to squeezed.
=> CA-285213 add error logging to memory interface

cluster/cluster_interface.ml, lib/xcp_service.ml, network/network_interface.ml
Don't merge until https://github.com/xapi-project/xs-opam/pull/236 has been merged and a new `xs-opam` released
=> network_interface: extend the abstract type declaration for compatibility with rpc 3.2.0

lib/xcp_pci.ml, network/network_interface.ml
This is for after rebase master then changes the interface to PPX.
=> Port sriov interface to ppx

storage/storage_interface.ml
Depends on these PRs:
https://github.com/xapi-project/xapi-storage/pull/79
https://github.com/xapi-project/xapi-storage-script/pull/61
https://github.com/xapi-project/xen-api/pull/3535
https://github.com/xenserver/xenadmin/pull/2014
Tested on feature/REQ477/probe-1 branch, with internal SR 81989, 81990, 81991. No new failures (there are existing known bugs with multipath and HBA, but they are unrelated to probe and appear on master as well)
I think all the commits should be squashed into one, we've been through a few iterations of this API according to the commit history, but it is not worth retaining that since you need to update all 3 repos everytime.
=> Review probe API changes for feature/REQ477/master

rrd/jbuild, storage/jbuild, storage/vdi_automaton.ml, storage/vdi_automaton_test.ml, xen/jbuild
With these the next necessary update will become an opam file update with a couple of library renames and nothing more
=> Backport of fixups made while porting idl to the new rpclib/rpclib-legacy packages

storage/jbuild, xcp.opam, xen/jbuild
This has to go in with https://github.com/xapi-project/xs-opam/pull/266 and the other related PRs
=> xcp.opam, {storage,xen}/jbuild: use the new rpc 5.0.0 and rpclib-legacy

lib/cohttp_posix_io.ml, lib/posix_channel.ml, lib/scheduler.ml, lib/xcp_client.ml, lib/xcp_service.ml, lib_test/idl_test_common.ml, network/network_stats.ml
In the few places where we use unsafe coercions, you can easily track the ownership of the bytes. They are always contained around the block that deals with them
=> xcp-idl: port to safe-strings without changing the interface

storage/storage_interface.ml, storage/storage_skeleton.ml
The return type of this new VDI.attach2 call is the same of that of the
Datapath.attach call in SMAPIv3. I've copied the types from SMAPIv3.
We cannot change the original VDI.attach call, because during SXM, older
xapis call Remote.VDI.attach, therefore changing it's return type would break
backward compatibility and SXM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xcp-idl/229)
=> [smapiv3 merge] Add new attach interface from SMAPIv3

lib_test/idl_test_common.ml
jbuilder runtest was failing with:
```
File "xcp-idl/lib_test/idl_test_common.ml", line 48, characters 31-171:
Error: Signature mismatch:
...
Values do not match:
val response_of_string : ?strict:bool -> string -> Rpc.response
is not included in
val response_of_string : string -> Rpc.response
File "xcp-idl/lib_test/idl_test_common.ml", line 42, characters 2-49:
Expected declaration
File "src/lib/jsonrpc.mli", line 26, characters 0-63:
Actual declaration
```
=> Fix build with rpclib 5.8.0

lib_test/idl_test_common.ml, storage/jbuild, storage/storage_interface.ml, storage/storage_skeleton.ml, storage/suite.ml, storage/vdi_automaton_test.ml, xcp.opam
This has been reviewed previously and had a nightly test run.
Has to be merged together with:
https://github.com/xapi-project/xcp-idl/pull/232
https://github.com/xapi-project/xapi-storage-script/pull/73
https://github.com/xapi-project/xapi-storage/pull/89
https://github.com/xapi-project/xen-api/pull/3645
https://github.com/xapi-project/xenopsd/pull/524
<specfile change>
=> [477 merge] CP-28132: VDI.attach2 interface and move to new rpclib

lib/debug.ml, lib/debug.mli, lib/jbuild, lib/xcp_service.ml, xcp.opam
We register our log reporter when an xcp service is configured, this way
we can report logs coming from libraries that use Logs. For example, we
can report errors in the cleanup function from stdext's finally.
For efficiency, we only consider logs of level warning and above from
libraries, to avoid calling our output_log function too often, which
does the actual filtering. It will be able to filter logs from libraries
too, the same way it filters them for toolstack components, because we
convert the Logs level and source to our own log level type and "brand".
Instead of using a shared Format.stbuf with str_formatter - this might
cause problems when logging from multiple threads - I decided to use a private buffer for the logs formatter.
=> CA-292641: Collect log messages from libs using Logs

xen/xenops_types.ml
Needs to be merged together with:
https://github.com/xapi-project/xcp-idl/pull/234
https://github.com/xapi-project/xen-api/pull/3675
https://github.com/xapi-project/xenopsd/pull/536
https://github.com/xapi-project/xenops-cli/pull/25
=> UEFI: add fields for VM.start

lib/task_server.ml, lib/task_server.mli, lib/updates.ml, lib/updates.mli
The Task and Updates generic code used by both the xen and storage
interfaces requires the interface code to be structured in a way that
is specific to the code produced by the camlp4 idl. This commit
makes it a bit easier to transition to the ppx-based idl.
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> Task/Updates: Remove dependence on camlp4 style interfaces

.travis.yml, lib_test/task_server_test.ml
8451d6ee343b36351a6b6e5b132f2bd5aa1ea393 updated the interface which
caused the tests to fail to build.
=> Fix unit tests: add missing functions

lib/task_server.ml, lib/task_server.mli, lib_test/task_server_test.ml, storage/storage_interface.ml, xen/xenops_interface.ml
Add a new field `cancellable` to Task. The default value is `true` which means
the task is cancellable.
=> CA-290696: Add field cancellable for task

xcp.opam, xen/jbuild
We no longer depends camlp4, so remove the dependency accordingly.
=> Remove useless dependency rpclib-legacy

storage/storage_interface.ml
This helper was duplicated between xapi and xenopsd. This helper belongs
here, it is useful for every user of the storage interface for
processing the return type of VDI.attach2.
=> storage_interface: add implementations_of_backend helper from xapi

network/network_interface.ml
=> network_interface: add Bridge_does_not_exist error

.travis.yml, lib/xcp_client.ml
It is much nicer to see `Xmlm.Error(1:1, "expected root element")`
than `Xmlm.Make(Buffer)(String).Error (_, -764030554)`.
I encountered the latter while setting up a new RPC server that wasn't replying with Xml properly on error, the better error message helped debugging the issue.
=> Register printer for Xmlm errors

lib/xcp_client.ml, varstore/privileged/varstore_privileged_client.ml, varstore/privileged/varstore_privileged_interface.ml
If varstored-guard is not running we do not want to block the xenopsd/XAPI thread forever.
The API call here should just create/destroy a socket, therefore should be fairly "quick",
20s ought to be more than enough even if the system is under high load.
We need the path parameter in stop, because the user id is no longer unique when we sandbox varstore-rm (there is no running domain associated with it).
=> CA-302981, CP-30032: Add a timeout to varstored-guard RPC calls, sandbox varstore-rm

xen/xenops_interface.ml, xen/xenops_types.ml
Adding the shutdown request that failed allows xapi to inform the users better.
Also since the `shutdown_request` type is going to be used both in `xen-api` and `xenopsd`, add it here.
=> CA: 272180: Make xenopsd report the request that makes a shutdown to fail

xen/xenops_interface.ml
This allows xapi to retrieve the information from Xen instead of roundabout methods, increasing robustness.
=> CP-30508: Expose iommu and hvm flags

xen/xenops_types.ml
Xapi need to pass the vGPU uuid to Xenopsd, and then to DEMU.
Signed-off-by: Michael Z <michael.zhao@citrix.com>
=> CP-31122: Add uuid in interface between Xapi and Xenopsd.

gpumon/gpumon_interface.ml, lib_test/test_data/gpumon/requests/get_vgpu_metadata.request.0
The vGPU uuid is needed in gpumon to filter metadata in case of multiple vGPUs.
Signed-off-by: Michael Z <michael.zhao@citrix.com>
=> CP-31124: Add uuid in interface between Xapi and Gpumon.

xen/xenops_interface.ml
The default value needs to be on the struct field, having the default value on the variant had no effect.
This is approach taken by other fields with default values, such as default_ipv4_configuration.
This might also be fixable in the ppx (propagate the default value from the variant to the struct field).
Needed by https://github.com/xapi-project/xenopsd/pull/622 where the unit tests need to create an empty Vif.t with all values filled in with defaults.
=> CP-31257: fix creation of default Vif.t

xen/xenops_types.ml
Signed-off-by: Lin Liu <lin.liu@citrix.com>
As titled, add support for extra_args for vgpu.
Customer can set extra args for the vgpu by command 
```xe vgpu-param-set uuid=xxxx extra_args="key1=v1,key2=v2"```
This is very similer to the previous verion of 
``` xe vm-param-set uuid=xxx platform:vgpu_extra_args="key1=v1,key2=v2"```
=> CP-31321: Support extra_args for vGPU configuration

.travis.yml, xen/xenops_interface.ml
A vGPU in SRIOV mode (non pass-through) has an associated virtual
function. This commit adds an address for it.
=> REQ-627 add optional PCI VF address to Vgpu.t

lib/debug.ml, lib/debug.mli, lib_test/debug_test.ml, varstore/deprivileged/dune, varstore/privileged/dune, xapi-idl.opam
This permits synchronous logging in critical, edge-case situations when dom0 is properly configured.
=> CA-322204: enable critical logging

memory/memory.ml
Current shim_mib calculation causes pv-shim to go out-of-memory and
panic for larger (>=8G) guests. The following memory usage has been
measured depending on the amount of guest RAM:
RAM   shim
------------------------------------
128M   shim used   15M pages 0xfa1
256M   shim used   17M pages 0x11a0
512M   shim used   19M pages 0x13a0
1G   shim used   25M pages 0x19a1
2G   shim used   35M pages 0x23a0
4G   shim used   54M pages 0x362e
8G   shim used   98M pages 0x6277
16G   shim used  187M pages 0xbb0b
32G   shim used  364M pages 0x16c36
64G   shim used  718M pages 0x2ce8a
128G   shim used 1429M pages 0x59532
Modify shim_mib formula in PVinPVH_memory_model_data accordingly.
Signed-off-by: Sergey Dyasli <sergey.dyasli@citrix.com>
=> CA-325843: Modify pv-shim (Xen 4.12) memory requirements

lib/debug.ml, lib/debug.mli
Syslog outputs it anyway, so it is pointless to include it twice in the
log line, and it complicates the Debug module of xcp-idl.
This removes a lock that we always took when outputting a log line.
=> CA-326244: do not include host name in log format

memory/memory.ml
Xen 4.12 --> 4.13 update makes pv-shim to use slightly more memory.
Modify the formula for shim_mib accordingly. Refer to the below table.
---------------------------------------
Guest    shim    curr     shim    new
RAM     4.12   formula   4.13  formula
---------------------------------------
128M     15M     21M     22M     24M
256M     17M     22M     24M     25M
512M     19M     25M     26M     28M
1G     25M     31M     32M     34M
2G     35M     42M     42M     45M
4G     54M     65M     61M     68M
8G     98M    111M    107M    114M
16G    187M    202M    198M    205M
32G    364M    384M    379M    387M
64G    718M    748M    743M    751M
128G   1429M   1476M   1472M   1479M
Signed-off-by: Sergey Dyasli <sergey.dyasli@citrix.com>
=> CA-327265: Modify shim_mib formula for Xen 4.13

xen/xenops_types.ml
Xen 4.13 needs to know ahead of time when a domain is going to use PCI
passtrough. This information needs to be conveyed to xenopsd. This
commit introduces the flag in the PV domain build information passed
from Xapi to Xenopsd. Such a flag already exists for HVM guests.
=> REQ-627 CA-328215 introduce pci_passthrough for PV

xen/xenops_interface.ml
The existing `features_hvm` and `features_pv` will continue to report
migration-safe CPUID flags.
The new fields will report the pool-leveling and VM boot-time CPUID flags.
There are certain CPUID features that are not present on the host, but still work
after a migration, albeit slowly: these will be present in `features_hvm`,
but absent from `features_hvm_host`.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
=> CP-32446: Introduce Xen.features_pv_host and Xen.features_hvm_host

cluster/cluster_interface.ml, lib/cohttp_posix_io.ml, memory/memory_interface.ml, varstore/privileged/varstore_privileged_interface.ml
Documentation in some places was annotated in strange ways which made upset odoc. ocaml-rpc should be compatible with ocamldoc's tags (https://github.com/mirage/ocaml-rpc/issues/139#issuecomment-562201548)
All the comments looked in the right place when I inspected the generated docs.
=> Documentation cleanup

.travis.yml, lib/debug.ml
It's been markes as deprecated and throws warnings
=> maintenance: replace references to pervasives module

xen/xenops_interface.ml
Quarantine domains require Xapi to dequarantine a PCI device in order to
set up its drivers. This commit adds an interface for such a call.
=> REQ-627 CA-333495 add PCI.dequarantine

lib_test/scheduler_test.ml
We got a failure in Jenkins:
```
ASSERT one_shot_success
--------------------------------------------------------------------------------
[failure] Error one_shot_success: expecting
true, got
false.
```
The test schedules a job for 1 second in the future and then checks that
it took `(0.99, 2.01) s` to run it.
But the scheduler, and indeed Thread.delay cannot make such guarantees.
It can only ensure that the job is scheduled *at least* 1 s in the future.
If the system is busy it can take 2s, 30s, 10m, etc. the kernel provides
no upper bound, this is not a real-time operating system.
Replace the strict check with a timeout based one instead: wait up to a
maximum allowed time, and then check how soon the callback actually got
invoked (i.e. that it didn't run too early).
We need the maximum …
=> Improve reliability of scheduler tests

memory/memory.ml
Xenguest currently crashes in a less than obvious manner if target set less than static-max. This allows DMC instead, and the guest boots
=> CA-334912: Allow DMC in PV Shim

network/network_interface.ml
The additions in this pull request are direct dependencies of xapi-project/xcp-networkd#173. Needed to allow the configuration/management of sr-iov networks in xapi, using adapters with already enabled sr-iov/vfs.
This pull request adds:
* `Sriov.enable_action_result`: `Manual_successful`, for manual sr-iov/vf configuration support
=> dependency of xapi-project/xcp-networkd#173 - allow use of already enabled sr-iov virtual functions in xapi managed sr-iov networks

network/network_interface.ml
This needs to be merged together with https://github.com/xapi-project/xen-api/pull/4051
=> Unrevert 'add Sriov.enable_action_result Manual_successful, for manual sr-iov/vf configuration support'

lib/xcp_client.ml, lib_test/idl_test_common.ml
There were two breaking changes affecting the tests:
- Avoiding marshalling integer as i8 requires the addition of the strict flag.
- A new function for json-rpc to have calls without responses got added
To test the changes I recommend to
* check out the xs-opam PR locally
* create a new opam switch and activate it
* add the local xs-opam repo to the switch with `opam repo add xs-opam-local location/to/xs-opam/folder`
* check out this PR and run `opam install --deps-only .` and `make test`
Depends on https://github.com/xapi-project/xs-opam/pull/511 and https://github.com/xapi-project/message-switch/pull/56
=> CP-34942: compatibility with rpclib 7 and 8

lib/debug.ml, lib/debug.mli
Allow callers of `with_thread_associated` to pass a client parameter which will be logged alongside a task's name
=> CP-35026 optionally include client info in logs

xen/xenops_interface.ml
This is a variant of `VM.import_metadata` that always queues the operation and
returns a task id immediately (like most VM operations). This is useful, once
the original (synchronous) function may block for longer periods while other
operations on the VM complete.
=> XSI-555/CA-347560: Add VM.import_metadata_async

xen/xenops_interface.ml
Backport of 83de389b.
This is a variant of `VM.import_metadata` that always queues the operation and
returns a task id immediately (like most VM operations). This is useful, once
the original (synchronous) function may block for longer periods while other
operations on the VM complete.
=> CA-347560: Add VM.import_metadata_async (Havana)
